name: Build and deploy
on: 
  pull_request:
    branches: 
      - main

jobs: 
  build_client:
    name: Build client
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
      - uses: actions/setup-node@v2
        name: Setup node 
        with:
          node-version: '14.1.0'
      - 
        env: 
          CI: false
        run: |
            cd client
            npm ci 
            npm run-script build
        name: Build client files
      - 
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        name: Docker login
      - run: | 
            cd client 
            docker build -f prod.dockerfile . -t tejashegde/messaging_app_client
            docker push tejashegde/messaging_app_client
        name: Docker build and push 
  build_api:
    name: Build api 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        name: Checkout code
      - 
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        name: Docker login
      - 
        run: |
              cd api 
              docker build -f prod.dockerfile . -t tejashegde/messaging_app_api
              docker push tejashegde/messaging_app_api
        name: Docker build and push
  compose_up: 
    name: docker-compose up
    runs-on: ubuntu-latest
    needs: 
      - build_api
      - build_client
    steps:
      - 
        uses: appleboy/ssh-action@master
        with:
            host: ec2-3-84-86-15.compute-1.amazonaws.com
            username: ubuntu  
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script_stop: true
            script: | 
              cd messagingApp/ 
              git pull origin main  
              docker-compose -f docker-compose.prof.yml up -d 
              exit 

